apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: say-hello
spec:
  params:
    - name: name
      description: Who should I say hello to?
      default: World
      type: string
  steps:
    - name: say-hello
      image: alpine
      command:
        - /bin/bash
      args: ['-c', 'echo hello $(params.name)']